info:
  component: Zuul Server

zuul:
  routes:
    customer:
      path: /customer/**
      serviceId: ihome-customer
    zuulserver:
      path: /self/**
      serviceId: zuul-server
    merchant:
      path: /merchant/**
      serviceId: ihome-merchant

server:
  port: 8768